### ISSUE TITLE
Just need some tests

### ISSUE THREAD

**Issue by kbroman** [mbernste/Tools4RR_Package#2]
The package looks good. I'd maybe split `createHist` into two functions: one that does the counting and one that makes the histogram. Or you could have the `createHist` function return the counts and add an argument indicating whether or not to also make the histogram figure. But it's fine as it is. 

You just need to add a test or two; see http://kbroman.org/pkg_primer/pages/tests.html

**Comment by mbernste** [comment]
Thank you for all the feedback in the issues you've opened.  I believe they are now all addressed.

**Comment by kbroman** [comment]
Looks good! I made a couple of other small changes, but you can call this done.
